host = "localhost"
port = 8080

[authentication]
admin_user = "root"
admin_password = "" # SHA256 hash
force_phone = false

[database]
driver = "sqlite3" # or "postgres", "sqlite3"
database = ":memory:"
pool_size = 500
user = "mtt"
password = "mtt"
host = "localhost"
port = 3306
#socket = "/var/run/mysqld/mysqld.sock"


[cache]
#driver = "redis" # or "builtin"
host = "localhost"
port = 6379
namespace = "mtt" # if driver is redis
username = ""
password = ""
session_key = "0000FFFF0000FFFF" # 32 bytes, in hex

[log]
access_log = "access.log"
error_log = "error.log"
level = "info"

[kubernetes]
secret = ""
namespace = ""
storage = ""

[custom]
title = "MTT Platform"
platform_name = "MTT Platform"